import { createServer } from 'node:http';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { SignalStore } from '../core/signals/signal-store.mjs';
import { ingestSignals } from '../core/signals/ingest-signals.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const store = new SignalStore(resolve(root, 'data/signals.json'));
const json = (response, status, value) => { response.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': '*' }); response.end(JSON.stringify(value)); };
const body = async (request) => { let text = ''; for await (const part of request) { text += part; if (text.length > 5_000_000) throw new Error('请求体过大'); } return JSON.parse(text || '{}'); };
const api = async (request, response) => { const url = new URL(request.url, 'http://localhost'); try { if (request.method === 'OPTIONS') { response.writeHead(204, { 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,DELETE,OPTIONS', 'access-control-allow-headers': 'content-type' }); return response.end(); } if (request.method === 'GET' && url.pathname === '/api/signals') return json(response, 200, { signals: await store.list() }); if (request.method === 'GET' && url.pathname.startsWith('/api/signals/')) { const signal = await store.get(decodeURIComponent(url.pathname.slice(13))); return signal ? json(response, 200, signal) : json(response, 404, { error: 'Signal 不存在' }); } if (request.method === 'POST' && url.pathname === '/api/signals/ingest') return json(response, 200, await ingestSignals(store, await body(request))); if (request.method === 'DELETE' && url.pathname.startsWith('/api/signals/')) return await store.delete(decodeURIComponent(url.pathname.slice(13))) ? json(response, 204, {}) : json(response, 404, { error: 'Signal 不存在' }); return json(response, 404, { error: '接口不存在' }); } catch (error) { return json(response, 400, { error: error.message || '请求未完成' }); } };
const production = process.argv.includes('--production');
if (production) { const { createReadStream, statSync } = await import('node:fs'); const dist = resolve(root, 'dist'); createServer(async (request, response) => { if (request.url.startsWith('/api/')) return api(request, response); try { const file = request.url === '/' ? resolve(dist, 'index.html') : resolve(dist, `.${request.url}`); if (!statSync(file).isFile()) throw new Error('not file'); createReadStream(file).pipe(response); } catch { createReadStream(resolve(dist, 'index.html')).pipe(response); } }).listen(5173, () => console.log('http://localhost:5173')); } else { const { createServer: createViteServer } = await import('vite'); const vite = await createViteServer({ configFile: resolve(root, 'apps/web/vite.config.mjs'), server: { middlewareMode: true } }); createServer((request, response) => request.url.startsWith('/api/') ? api(request, response) : vite.middlewares(request, response)).listen(5173, () => console.log('http://localhost:5173')); }
