import { useEffect, useMemo, useState } from "react";
import { connectRetrievalAccount, getContentBreakdownStatus, getRetrievalConnection, requestContentBreakdown, saveExternalCase, scanHotContent, setHotContentIntent } from "../api/hot-content";
import { getWorkspace } from "../api/workspace";
import { connectionStatusLabels, labelOf } from "../display-labels";
import { UiIcon } from "../components/UiIcon";
import { PageHeader } from "../components/PageHeader";
import { StatusTag } from "../components/StatusTag";
import { formatDateTime, formatMetricValue } from "../utils/formatters";

const filters = [["all", "全部"], ["group", "近期多人在发"], ["outlier", "小博主异常爆款"]];
const breakdownWaitMs = 8 * 60 * 1000;
const pollDelayMs = 2500;
const display = (value) => value === null || value === undefined || value === "" ? "未显示" : value;
const followerText = (value) => value === null || value === undefined || value === "" ? "未显示" : `${value} 粉丝`;
const connectionTone = (status) => status === "CONNECTED" ? "green" : status === "CONNECTING" ? "orange" : "neutral";
const connectionEmpty = (status) => ({
  CONNECTING: ["正在连接检索小号", "请在浏览器中完成登录，连接完成后即可开始检索。"],
  LOGIN_REQUIRED: ["请先登录检索小号", "登录后即可读取公开可见内容。"],
  PAGE_CLOSED: ["检索页已关闭，请重新连接", "重新打开检索页后即可继续读取公开可见内容。"],
  NOT_CONNECTED: ["检索小号未连接", "连接并登录检索小号后，即可读取本次可见内容。"],
}[status] || ["检索暂不可用", "请检查连接状态后重试。"]);
function summaryFor(candidate, analysis, outlier) { return analysis?.likelyPrimaryFactors?.[0] || outlier?.whyFound || candidate.description || "当前可见信息有限，建议查看完整分析后再判断。"; }
function reasonFor(candidate, groups, outlier) { const grouped = groups.find((group) => group.candidateIds?.includes(candidate.id)); return outlier?.status === "observed" ? outlier.whyFound : grouped?.whyFound || "来自本次可见内容检索，等待进一步判断。"; }

export function HotContentPage({ workspace, onWorkspaceChanged }) {
  const [pageWorkspace, setPageWorkspace] = useState(workspace);
  const hot = pageWorkspace.hotContent || {};
  const [connection, setConnection] = useState(null); const [connectionLoading, setConnectionLoading] = useState(true); const [filter, setFilter] = useState("all"); const [expandedId, setExpandedId] = useState(null); const [pendingBreakdown, setPendingBreakdown] = useState(null); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { setPageWorkspace(workspace); }, [workspace]);
  useEffect(() => { let active = true; getWorkspace().then((result) => { if (active) setPageWorkspace(result); }).catch(() => active && setError("暂时无法刷新页面内容，请稍后重试。")).finally(() => active && setConnectionLoading(false)); return () => { active = false; }; }, []);
  useEffect(() => { let active = true; getRetrievalConnection().then((result) => { if (active) setConnection(result); }).catch(() => active && setError("暂时无法读取连接状态，请稍后重试。")).finally(() => active && setConnectionLoading(false)); return () => { active = false; }; }, []);
  const status = connection?.status || pageWorkspace.xhsRead?.status || "NOT_CONNECTED"; const candidates = hot.candidates || []; const groups = hot.groups || []; const outliers = hot.outliers || []; const analyses = hot.analyses || [];
  const visibleCandidates = useMemo(() => candidates.filter((candidate) => filter === "group" ? groups.some((group) => group.candidateIds?.includes(candidate.id)) : filter === "outlier" ? outliers.some((item) => item.candidateId === candidate.id && item.status === "observed") : true), [candidates, filter, groups, outliers]);
  useEffect(() => { if (!pendingBreakdown) return undefined; let active = true; let timer; const finishFailed = () => { if (!active) return; setPendingBreakdown(null); setError("完整分析暂未完成，请稍后重试。"); }; const check = async () => { if (Date.now() >= pendingBreakdown.deadline) return finishFailed(); try { const result = await getContentBreakdownStatus(pendingBreakdown.jobId); if (!active) return; if (result.status === "completed") { setPendingBreakdown(null); setExpandedId(pendingBreakdown.candidateId); setNotice("完整分析已更新。"); await onWorkspaceChanged(); return; } if (result.status === "failed") return finishFailed(); } catch { /* Continue until the known deadline, then show a fixed user-facing message. */ } if (active) timer = window.setTimeout(check, pollDelayMs); }; check(); return () => { active = false; window.clearTimeout(timer); }; }, [onWorkspaceChanged, pendingBreakdown]);
  useEffect(() => { if (status !== "CONNECTING") return undefined; let active = true; let timer; const check = async () => { try { const result = await getRetrievalConnection(); if (!active) return; setConnection(result); if (result.status !== "CONNECTING") { await onWorkspaceChanged(); return; } } catch { if (active) setError("暂时无法更新连接状态，请稍后重试。"); } if (active) timer = window.setTimeout(check, pollDelayMs); }; check(); return () => { active = false; window.clearTimeout(timer); }; }, [onWorkspaceChanged, status]);
  async function run(action, successMessage, key) { setBusy(key); setError(""); setNotice(""); try { const result = await action(); await onWorkspaceChanged(); setNotice(successMessage); return result; } catch { setError("操作未完成，请稍后重试。"); return null; } finally { setBusy(""); } }
  async function connect() { const result = await run(connectRetrievalAccount, "已打开检索小号连接，请在浏览器中完成登录后开始检索。", "connect"); if (result) setConnection(result.xhsRead || { status: "CONNECTING" }); }
  async function scan() { const result = await run(() => scanHotContent(), "本次可见内容已更新。", "scan"); if (result) setConnection(result.xhsRead || { status: "CONNECTED" }); }
  async function changeIntent(id, intent, message) { await run(() => setHotContentIntent(id, intent), message, `${intent}-${id}`); }
  async function addToKnowledge(candidate) { await run(() => saveExternalCase(candidate), "已加入知识库，后续可继续补充判断。", `knowledge-${candidate.id}`); }
  async function breakdown(candidate) { const existing = analyses.find((item) => item.contentCandidateId === candidate.id); if (existing?.breakdownStatus === "completed") { setExpandedId(expandedId === candidate.id ? null : candidate.id); return; } setBusy(`breakdown-${candidate.id}`); setError(""); setNotice(""); try { const result = await requestContentBreakdown(candidate.id); if (!result?.id) throw new Error("missing result"); const startedAt = new Date(result.startedAt || result.createdAt || Date.now()).getTime(); setPendingBreakdown({ candidateId: candidate.id, jobId: result.id, deadline: Math.max(Date.now() + breakdownWaitMs, startedAt + breakdownWaitMs) }); setNotice("完整分析正在整理，完成后会自动更新。"); } catch { setError("操作未完成，请稍后重试。"); } finally { setBusy(""); } }
  return <>
    <PageHeader title="热点 / 爆款" description="从检索小号读取可见内容，保留值得继续判断的真实线索。" actions={<button className="button button--primary" onClick={scan} disabled={busy !== "" || status !== "CONNECTED"}><UiIcon name="search" size={19} />{busy === "scan" ? "正在检索" : "开始检索"}</button>} />
    {(notice || error) && <div className={error ? "page-message page-message--error" : "page-message"}>{error || notice}</div>}
    <section className="hot-connection-card"><div className="hot-connection-copy"><span className="section-symbol"><UiIcon name="search" size={18} /></span><div><h2>检索小号连接状态</h2><p>仅用于检索公开可见内容，不会用于发布或操作主账号。</p></div></div><div className="hot-connection-actions"><StatusTag tone={connectionLoading ? "blue" : connectionTone(status)}>{connectionLoading ? "正在读取" : labelOf(connectionStatusLabels, status, "暂不可用")}</StatusTag><button className="button button--secondary hot-connect-button" onClick={connect} disabled={connectionLoading || busy !== "" || status === "CONNECTED" || status === "CONNECTING"}>{busy === "connect" || status === "CONNECTING" ? "正在连接" : status === "CONNECTED" ? "已连接" : "连接检索小号"}</button></div></section>
    <section className="hot-content-section"><div className="hot-section-top"><div><h2>本次可见内容</h2><p>{hot.updatedAt ? `最近检索：${formatDateTime(hot.updatedAt, "未显示")}` : "尚未开始检索"}</p></div><div className="hot-filter-tabs" aria-label="内容筛选">{filters.map(([key, name]) => <button key={key} className={filter === key ? "hot-filter-tab hot-filter-tab--active" : "hot-filter-tab"} onClick={() => setFilter(key)} aria-pressed={filter === key}>{name}</button>)}</div></div>
      {status !== "CONNECTED" && !candidates.length ? <div className="hot-empty-state"><strong>{connectionEmpty(status)[0]}</strong><p>{connectionEmpty(status)[1]}</p></div> : !candidates.length ? <div className="hot-empty-state"><strong>暂无可见内容</strong><p>开始检索后，符合条件的内容会显示在这里。</p></div> : !visibleCandidates.length ? <div className="hot-empty-state"><strong>当前筛选下暂无内容</strong><p>可切换到“全部”，查看本次检索到的内容。</p></div> : <div className="hot-list">{visibleCandidates.map((candidate) => {
        const analysis = analyses.find((item) => item.contentCandidateId === candidate.id); const outlier = outliers.find((item) => item.candidateId === candidate.id); const ignored = hot.ignoredIds?.includes(candidate.id); const marked = hot.markedForTopicIds?.includes(candidate.id); const expanded = expandedId === candidate.id; const waiting = pendingBreakdown?.candidateId === candidate.id;
        return <article className={ignored ? "hot-card hot-card--muted" : "hot-card"} key={candidate.id}><div className="hot-card-main"><div className="hot-card-heading"><div><h3>{display(candidate.title)}</h3><p>{display(candidate.authorName)} <i /> {followerText(candidate.authorFollowerCount)} <i /> {formatDateTime(candidate.publishedAt, "未显示")}</p></div>{marked && <StatusTag tone="red">已用于选题</StatusTag>}{ignored && <StatusTag tone="neutral">已忽略</StatusTag>}</div><dl className="hot-metrics"><div><dt>点赞</dt><dd>{formatMetricValue("likes", candidate.likeCount)}</dd></div><div><dt>收藏</dt><dd>{formatMetricValue("favorites", candidate.favoriteCount)}</dd></div><div><dt>评论</dt><dd>{formatMetricValue("comments", candidate.commentCount)}</dd></div><div><dt>转发</dt><dd>{formatMetricValue("shares", candidate.shareCount)}</dd></div></dl><div className="hot-insight"><strong>发现原因</strong><p>{reasonFor(candidate, groups, outlier)}</p></div><div className="hot-insight"><strong>分析摘要</strong><p>{summaryFor(candidate, analysis, outlier)}</p></div></div><div className="hot-card-actions"><button className="card-action" onClick={() => breakdown(candidate)} disabled={busy !== "" || waiting}>{busy === `breakdown-${candidate.id}` || waiting ? "正在整理" : expanded ? "收起完整分析" : "查看完整分析"}<UiIcon name="arrow" size={17} /></button><button className="card-action" onClick={() => addToKnowledge(candidate)} disabled={busy !== ""}>加入知识库</button><button className="card-action" onClick={() => changeIntent(candidate.id, "topic", "已标记为可用于选题。") } disabled={busy !== ""}>用于选题</button><button className="card-action card-action--quiet" onClick={() => changeIntent(candidate.id, "ignore", "已忽略这条内容。") } disabled={busy !== ""}>忽略</button></div>{expanded && <div className="hot-detail"><strong>完整分析</strong><p>{analysis?.titleAnalysis?.observation || "暂未取得更多可用信息。"}</p><p>{analysis?.titleAnalysis?.inference || analysis?.likelyPrimaryFactors?.[0] || "当前无法稳定判断具体原因。"}</p>{analysis?.evidenceLimits?.length ? <small>判断边界：{analysis.evidenceLimits[0]}</small> : null}</div>}</article>;
      })}</div>}</section>
  </>;
}
