import { useEffect, useMemo, useState } from "react";
import { addOwnedMaterialToKnowledge, createManualKnowledge, deleteKnowledgeItem, deleteKnowledgePattern, getKnowledgeContext } from "../api/knowledge";
import { labelOf, maturityLabels } from "../display-labels";
import { AsyncState } from "../components/AsyncState";
import { PageHeader } from "../components/PageHeader";
import { StatusTag } from "../components/StatusTag";
import { UiIcon } from "../components/UiIcon";
import { formatDateTime } from "../utils/formatters";
import "./KnowledgePage.css";

const tabs = [["all", "全部"], ["external", "爆款案例"], ["title", "标题方法"], ["hook", "Hook 方法"], ["structure", "内容结构"], ["materials", "我的材料"], ["learning", "账号经验"]];
const blank = (value) => value === null || value === undefined || value === "";
const display = (value, fallback = "暂无") => blank(value) ? fallback : value;
const itemLabel = (type) => ({ external_case: "外部案例", owned_material: "我的材料", own_account_learning: "账号经验", manual_note: "我的笔记" }[type] || "知识记录");
const patternLabel = (type) => ({ title: "标题方法", hook: "Hook 方法", structure: "内容结构", cover: "封面方法" }[type] || "内容方法");
const patternTone = (maturity) => maturity === "validated" ? "green" : maturity === "supported" ? "blue" : maturity === "contradicted" ? "orange" : "neutral";

export function KnowledgePage({ workspace, onWorkspaceChanged }) {
  const [context, setContext] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [tab, setTab] = useState("all"); const [busy, setBusy] = useState(""); const [showForm, setShowForm] = useState(false); const [draft, setDraft] = useState({ title: "", summary: "", userNotes: "", tags: "" });
  const refresh = async () => { setLoading(true); setError(""); try { setContext(await getKnowledgeContext()); } catch { setError("暂时无法读取知识库，请稍后重试。"); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  const items = context?.items || []; const patterns = context?.patterns || []; const materials = workspace?.accountMaterials || [];
  const savedMaterialIds = useMemo(() => new Set(items.filter((item) => item.type === "owned_material").flatMap((item) => item.sourceMaterialIds || [])), [items]);
  const filtered = useMemo(() => {
    if (tab === "external") return { items: items.filter((item) => item.type === "external_case"), patterns: [] };
    if (tab === "materials") return { items: items.filter((item) => item.type === "owned_material" || item.type === "manual_note"), patterns: [] };
    if (tab === "learning") return { items: items.filter((item) => item.type === "own_account_learning"), patterns: [] };
    if (["title", "hook", "structure"].includes(tab)) return { items: [], patterns: patterns.filter((pattern) => pattern.patternType === tab) };
    return { items, patterns };
  }, [items, patterns, tab]);
  async function run(action, success, key) { setBusy(key); setError(""); setNotice(""); try { await action(); await Promise.all([refresh(), onWorkspaceChanged()]); setNotice(success); return true; } catch { setError("操作未完成，请稍后重试。"); return false; } finally { setBusy(""); } }
  const saveMaterial = (material) => run(() => addOwnedMaterialToKnowledge(material.materialId), "已加入知识库，可在选题和创作中作为真实材料使用。", `material-${material.materialId}`);
  async function saveNote(event) { event.preventDefault(); if (!draft.title.trim()) { setError("请先填写笔记名称。"); return; } const tags = draft.tags.split("，").flatMap((value) => value.split(",")).map((value) => value.trim()).filter(Boolean); const saved = await run(() => createManualKnowledge({ ...draft, tags }), "已保存我的笔记。", "manual-note"); if (saved) { setDraft({ title: "", summary: "", userNotes: "", tags: "" }); setShowForm(false); setTab("materials"); } }
  async function removeItem(item) { if (!window.confirm(`确定移除“${item.title || "这条记录"}”吗？`)) return; await run(() => deleteKnowledgeItem(item.id), "已移除这条知识记录。", `delete-item-${item.id}`); }
  async function removePattern(pattern) { if (!window.confirm(`确定移除“${pattern.name || "这条内容方法"}”吗？`)) return; await run(() => deleteKnowledgePattern(pattern.id), "已移除这条内容方法。", `delete-pattern-${pattern.id}`); }
  return <>
    <PageHeader title="知识库" description="沉淀外部案例、我的真实材料与账号经验，为选题和创作提供依据。" actions={<button className="button button--secondary knowledge-add-button" onClick={() => setShowForm(!showForm)}>{showForm ? "收起笔记" : "记录我的笔记"}</button>} />
    {(notice || error) && <div className={error ? "page-message page-message--error" : "page-message"}>{error || notice}</div>}
    {showForm && <form className="knowledge-note-form" onSubmit={saveNote}><div className="knowledge-section-heading"><div><span className="section-symbol"><UiIcon name="writing" size={17} /></span><div><h2>记录我的笔记</h2><p>仅保存你自己补充的内容，不会替代已有的真实案例或账号经验。</p></div></div></div><div className="knowledge-note-grid"><label>笔记名称<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="例如：下次内容想验证的表达方式" maxLength={240} /></label><label>标签（可选）<input value={draft.tags} onChange={(event) => setDraft({ ...draft, tags: event.target.value })} placeholder="用逗号分隔" /></label><label className="knowledge-note-wide">摘要（可选）<textarea value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} placeholder="记录这条笔记的背景或内容。" maxLength={3000} /></label><label className="knowledge-note-wide">补充说明（可选）<textarea value={draft.userNotes} onChange={(event) => setDraft({ ...draft, userNotes: event.target.value })} placeholder="写下之后使用时需要注意的内容。" maxLength={3000} /></label></div><div className="knowledge-form-actions"><button className="button button--primary knowledge-save-button" type="submit" disabled={busy !== ""}>{busy === "manual-note" ? "正在保存" : "保存笔记"}</button></div></form>}
    {loading ? <AsyncState state="loading" /> : !context ? <AsyncState state="error" description={error || "暂时无法读取知识库。"} onRetry={refresh} /> : <><section className="knowledge-intro"><div className="knowledge-source-note knowledge-source-note--external"><span><UiIcon name="search" size={17} /></span><div><strong>外部候选经验</strong><p>来自公开可见内容，只能作为观察与参考，不代表已在你的账号验证。</p></div></div><div className="knowledge-source-note knowledge-source-note--own"><span><UiIcon name="account" size={17} /></span><div><strong>我的主账号真实经验</strong><p>来自你的材料与复盘记录，可追溯到实际内容或用户确认。</p></div></div></section><section className="knowledge-section"><div className="knowledge-tabs" aria-label="知识库分类">{tabs.map(([key, name]) => <button key={key} className={tab === key ? "knowledge-tab knowledge-tab--active" : "knowledge-tab"} onClick={() => setTab(key)} aria-pressed={tab === key}>{name}</button>)}</div>{tab === "materials" && <div className="knowledge-material-source"><div><h2>账号材料</h2><p>先在“我的账号”上传材料，再按需加入知识库。</p></div>{!materials.length ? <p className="knowledge-inline-empty">暂无账号材料</p> : <div className="knowledge-material-list">{materials.map((material) => <article key={material.materialId}><div><strong>{display(material.name, "未命名材料")}</strong><p>{material.kind === "image" ? "图片材料" : "文本材料"} <i /> {formatDateTime(material.createdAt, "时间未提供")}</p></div>{savedMaterialIds.has(material.materialId) ? <StatusTag tone="green">已加入</StatusTag> : <button className="button button--secondary knowledge-material-button" onClick={() => saveMaterial(material)} disabled={busy !== ""}>{busy === `material-${material.materialId}` ? "正在加入" : "加入知识库"}</button>}</article>)}</div>}</div>}{!filtered.items.length && !filtered.patterns.length ? <div className="knowledge-empty"><strong>{tab === "all" ? "知识库暂时为空" : "当前分类暂无内容"}</strong><p>{tab === "materials" ? "可先从“我的账号”上传真实材料，再加入知识库。" : "后续保存案例、材料或复盘经验后，会显示在这里。"}</p></div> : <div className="knowledge-content-grid">{filtered.items.map((item) => <KnowledgeItem key={item.id} item={item} busy={busy} onDelete={removeItem} />)}{filtered.patterns.map((pattern) => <KnowledgePattern key={pattern.id} pattern={pattern} busy={busy} onDelete={removePattern} />)}</div>}</section></>}
  </>;
}

function KnowledgeItem({ item, busy, onDelete }) { const external = item.type === "external_case"; const own = item.type === "own_account_learning" || item.type === "owned_material"; const detail = item.summary || item.userNotes; return <article className={`knowledge-card ${external ? "knowledge-card--external" : own ? "knowledge-card--own" : ""}`}><div className="knowledge-card-top"><StatusTag tone={external ? "orange" : own ? "green" : "blue"}>{itemLabel(item.type)}</StatusTag><button className="knowledge-remove" onClick={() => onDelete(item)} disabled={busy !== ""} aria-label={`移除${display(item.title, "这条记录")}`}>{busy === `delete-item-${item.id}` ? "处理中" : "移除"}</button></div><h3>{display(item.title, "未命名记录")}</h3>{item.authorName && <p className="knowledge-card-meta">作者：{item.authorName}</p>}<p className={detail ? "knowledge-card-copy" : "knowledge-card-copy knowledge-card-copy--muted"}>{display(detail, "暂无补充说明")}</p>{item.tags?.length ? <div className="knowledge-tags">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div> : null}<div className="knowledge-card-foot"><span>{external ? "保存时间" : "记录时间"}：{formatDateTime(item.updatedAt || item.capturedAt, "时间未提供")}</span>{item.xhsUrl ? <a href={item.xhsUrl} target="_blank" rel="noreferrer">查看原内容 <UiIcon name="arrow" size={14} /></a> : null}</div></article>; }
function KnowledgePattern({ pattern, busy, onDelete }) { const sourceCount = Array.isArray(pattern.sourceKnowledgeIds) ? pattern.sourceKnowledgeIds.length : "暂无"; return <article className="knowledge-card knowledge-card--pattern"><div className="knowledge-card-top"><StatusTag tone="blue">{patternLabel(pattern.patternType)}</StatusTag><StatusTag tone={patternTone(pattern.maturity)}>{labelOf(maturityLabels, pattern.maturity, "待确认")}</StatusTag></div><h3>{display(pattern.name, "未命名内容方法")}</h3><p className={pattern.description ? "knowledge-card-copy" : "knowledge-card-copy knowledge-card-copy--muted"}>{display(pattern.description, "暂无补充说明")}</p><div className="knowledge-pattern-foot"><span>参考记录：{sourceCount}</span><button className="knowledge-remove" onClick={() => onDelete(pattern)} disabled={busy !== ""}>{busy === `delete-pattern-${pattern.id}` ? "处理中" : "移除"}</button></div></article>; }
